---
- name: Production Switchover from EIGRP to OSPFv3
  hosts: RoutersSWOver
  gather_facts: false

  tasks:

  - name: Enable IPv6 unicast routing
    cisco.ios.ios_config:
        lines: ipv6 unicast-routing

  - name: Create OSPFv3 process
    cisco.ios.ios_ospfv3:
      config:
        processes: 
          - process_id: "{{ ospfv3_pid }}"
            address_family:
              - afi: ipv4
                unicast: true 
                router_id: "{{ ospfv3_rid }}"
              - afi: ipv6
                unicast: true
                router_id: "{{ ospfv3_rid }}"
  
  - name: Modify transit interfaces for OSPFv3 IPv4/v6 AFI 
    cisco.ios.ios_ospf_interfaces:
      config:
        - name: "{{ ospfv3_int_in }}"
          address_family:
            - afi: ipv4
              process:
                id: "{{ ospfv3_pid }}"
                area_id: 0
            - afi: ipv6
              process:
                id: "{{ ospfv3_pid }}"
                area_id: 0
        - name: "{{ ospfv3_int_out }}"
          address_family:
            - afi: ipv4
              process:
                id: "{{ ospfv3_pid }}"
                area_id: 0
            - afi: ipv6
              process:
                id: "{{ ospfv3_pid }}"
                area_id: 0
      state: merged    
            

                